run:
  timeout: 10m

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/bank-vaults/bank-vaults)
  goimports:
    local-prefixes: github.com/bank-vaults/bank-vaults

linters:
  enable-all: true
  disable:
    - maligned
    - funlen
    - dupl
    - nestif
    - wsl
    - lll
    - interfacer
    - exhaustivestruct
    - nlreturn

    #deprecated
    - ifshort
    - varcheck
    - structcheck
    - deadcode
    - golint
    - scopelint
    - nosnakecase

    # TODO: fixme
    - paralleltest
    - forcetypeassert
    - wrapcheck
    - exportloopref
    - cyclop
    - godox
    - godot
    - gomnd
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocognit
    - gocritic
    - stylecheck
    - gocyclo
    - testpackage
    - varnamelen
    - ireturn
    - exhaustruct
    - nonamedreturns
    - nilnil
    - maintidx
    - gosec
    - gomoddirectives
    - gci
    - gofumpt
    - gofmt
    - goimports
    - revive
    - staticcheck
    - depguard
