name: CI
on: [pull_request]
env:
  GO_VERSION: 1.19.2
jobs:

  checks:
    name: Checks
    runs-on: ubuntu-latest

    services:
      vault:
        image: vault:1.6.2
        env:
          SKIP_SETCAP: true
          VAULT_DEV_ROOT_TOKEN_ID: 227e1cce-6bf7-30bb-2d2a-acc854318caf
        ports:
          - 8200:8200

    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # chart testing fails otherwise

    - name: Check licenses
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: make license-check

    - name: Setup test dependencies
      run: |
        sudo apt install opensc softhsm
        sudo mkdir -p /var/lib/softhsm/tokens/
        sudo softhsm2-util --init-token --free --label bank-vaults --so-pin banzai --pin banzai
        sudo pkcs11-tool --module /usr/lib/softhsm/libsofthsm2.so --keypairgen --key-type rsa:2048 --pin banzai --token-label bank-vaults --label bank-vaults
        sudo chown -R runner:docker /etc/softhsm /var/lib/softhsm

    - name: Run verification
      run: make check
      env:
        VAULT_TOKEN: 227e1cce-6bf7-30bb-2d2a-acc854318caf

  build-bank-vaults:
    name: Build bank-vaults
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          tags: bank-vaults:latest
          outputs: type=docker,dest=/tmp/bank-vaults.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bank-vaults
          path: /tmp/bank-vaults.tar
